services:
  db:
    image: postgres:18-trixie
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

  apache:
    image: apache_application_sviluppo:latest
    container_name: apache_application_sviluppo
    build: 
      context: .
      dockerfile: Dockerfile-apache-sviluppo
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    depends_on:
      - db

  app:
    image: python_application:latest
    container_name: python_application
    build: 
      context: .
      dockerfile: Dockerfile-python
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    depends_on:
      - db

volumes:
  postgres-data: