FROM python:3.14-slim-trixie

RUN apt-get update && apt-get install -y libpq-dev gcc iputils-ping dnsutils git apache2 iproute2 && apt-get clean

RUN sed -i 's/Listen\ 80/Listen\ 8080/' /etc/apache2/ports.conf
RUN sed -i '/Listen 8080/a Listen 80' /etc/apache2/ports.conf

RUN rm -f /etc/apache2/sites-enabled/000-default.conf
COPY apache/virtualhost0.conf /etc/apache2/sites-enabled/virtualhost0.conf

COPY apache/http/index.html /var/www/html/index.html
COPY apache/http/script.js  /var/www/html/script.js
COPY apache/http/favicon.ico /var/www/html/favicon.ico

COPY apache/entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod +x /usr/local/bin/entrypoint.sh

WORKDIR /workspace

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]