FROM debian:trixie-slim

RUN apt-get update && apt install --no-install-recommends -y openjdk-21-jdk-headless libpq-dev gcc iputils-ping dnsutils git && apt-get clean

WORKDIR /workspace

#COPY requirements.txt .
#RUN pip install --no-cache-dir -r requirements.txt

# Keep the container running infinitely so VS Code can connect to it
CMD ["sleep", "infinity"]